services:
  backend:
    build: 
      context: .
      dockerfile: backend.Dockerfile
    hostname: backend
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "8000:7000"
    hostname: frontend